runtime: python38

service: default

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  support: "https://support-dot-enterprise-iap-use-cases.uc.r.appspot.com/"
